/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Ejercicio1 extends javax.swing.JFrame {

    private double numero1 = 0;
    private String operador = "";
    private boolean nuevoNumero = true;
    
    public Ejercicio1() {
        initComponents();
        configurarCalculadora();
    }
    
    
    private void configurarCalculadora(){
        // ActionListener para los botones numéricos
        ActionListener listenerNumeros = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JButton boton = (JButton) e.getSource();
                
                if (nuevoNumero) {
                    txtResultado.setText("");
                    nuevoNumero = false;
                }
                
                txtResultado.setText(txtResultado.getText() + boton.getText());
            }
        };
        
        // Asignar el listener a todos los botones numéricos
        btn0.addActionListener(listenerNumeros);
        btn1.addActionListener(listenerNumeros);
        btn2.addActionListener(listenerNumeros);
        btn3.addActionListener(listenerNumeros);
        btn4.addActionListener(listenerNumeros);
        btn5.addActionListener(listenerNumeros);
        btn6.addActionListener(listenerNumeros);
        btn7.addActionListener(listenerNumeros);
        btn8.addActionListener(listenerNumeros);
        btn9.addActionListener(listenerNumeros);
        
        // Configurar botones de operaciones
        btnSumar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                prepararOperacion("+");
            }
        });
        
        btnRestar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                prepararOperacion("-");
            }
        });
        
        btnMultiplicar.addActionListener(new ActionListener() { 
            @Override
            public void actionPerformed(ActionEvent e) {
                prepararOperacion("*");
            }
        });
        
        btnDividir.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                prepararOperacion("/");
            }
        });
    }
    
    private void prepararOperacion(String op) {
        if (!txtResultado.getText().isEmpty()) {
            numero1 = Double.parseDouble(txtResultado.getText());
            operador = op;
            nuevoNumero = true;
        }
    }
    
    
    
    
    private void limpiar() {
        txtResultado.setText("");
        numero1 = 0;
        operador = "";
        nuevoNumero = true;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtResultado = new javax.swing.JTextField();
        lblResultado = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        panel3 = new javax.swing.JPanel();
        btnIgual = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 110, -1));

        lblResultado.setText("Resultado");
        jPanel1.add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 60, -1));

        btnLimpiar.setText("C");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 40, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn1.setText("1");
        jPanel2.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 40, -1));

        btn2.setText("2");
        jPanel2.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 40, -1));

        btn3.setText("3");
        jPanel2.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 40, -1));

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 40, -1));

        btn5.setText("5");
        jPanel2.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 40, -1));

        btn6.setText("6");
        jPanel2.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 40, -1));

        btn7.setText("7");
        jPanel2.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 40, -1));

        btn8.setText("8");
        jPanel2.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 40, -1));

        btn9.setText("9");
        jPanel2.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 40, -1));

        btn0.setText("0");
        jPanel2.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, -1));

        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        panel3.add(btnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 73, 70, 20));

        btnSumar.setText("+");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });
        panel3.add(btnSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 50, -1));

        btnDividir.setText("/");
        panel3.add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 50, -1));

        btnRestar.setText("-");
        panel3.add(btnRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 50, -1));

        btnMultiplicar.setText("*");
        panel3.add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_btn4ActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        if (!txtResultado.getText().isEmpty() && !operador.isEmpty()) {
        try {
            double numero2 = Double.parseDouble(txtResultado.getText());
            double resultado = 0;
            
            switch(operador) {
                case "+":
                    resultado = numero1 + numero2;
                    break;
                case "-":
                    resultado = numero1 - numero2;
                    break;
                case "*":
                    resultado = numero1 * numero2;
                    break;
                case "/":
                    if (numero2 != 0) {
                        resultado = numero1 / numero2;
                    } else {
                        JOptionPane.showMessageDialog(this, 
                            "No se puede dividir por cero", 
                            "Error", 
                            JOptionPane.ERROR_MESSAGE);
                        limpiar();
                        return;
                    }
                    break;
            }
            
            // Mostrar resultado (sin decimales si es número entero)
            if (resultado == (int)resultado) {
                txtResultado.setText(String.valueOf((int)resultado));
            } else {
                txtResultado.setText(String.valueOf(resultado));
            }
            
            operador = "";
            nuevoNumero = true;
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Error en el formato del número", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            limpiar();
        }
    }
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JPanel panel3;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
